-- Create table for Vietnamese recipes
CREATE TABLE vietnamese_recipes (
    recipe_id VARCHAR(20) PRIMARY KEY,
    recipe_name VARCHAR(100) NOT NULL,
    description TEXT,
    image_file VARCHAR(255)
);

-- Create table for Chinese recipes
CREATE TABLE chinese_recipes (
    recipe_id VARCHAR(20) PRIMARY KEY,
    recipe_name VARCHAR(100) NOT NULL,
    description TEXT,
    image_file VARCHAR(255)
);

-- Insert data for Vietnamese recipes
INSERT INTO vietnamese_recipes (recipe_id, recipe_name, description, image_file) VALUES
('VN-0001','Banh Canh Cua (Vietnamese Shrimps and Crab Thick Noodle Soup)', 'Banh Canh Cua is a comforting Vietnamese noodle soup made with thick, chewy noodles, crab meat, shrimp, and a flavorful broth. It''s a popular dish enjoyed throughout Vietnam, especially during colder months.', 'data/images/viD_img/Banh Canh Cua (Vietnames Shrimps n Crab Thick Noodle Soup).jpg'),
('VN-0002','Banh Xeo (Vietnamese Crispy Savory Pancake)', 'Banh Xeo is a popular Vietnamese street food dish consisting of a crispy, savory pancake filled with shrimp, pork, bean sprouts, and herbs. It''s often served with lettuce leaves and dipped in a tangy and savory sauce.', 'data/images/viD_img/Banh Xeo (Vietnamese Crispy Ssavory Pancake) 1.jpg'),
('VN-0003','Bo Bia (Vietnamese Spring Rolls with Jicama n Egg)', 'Bo Bia is a Vietnamese spring roll filled with jicama, carrots, Chinese sausage, egg, and dried shrimp. It''s wrapped in rice paper and served with a sweet and savory dipping sauce. Bo Bia is a popular street food snack in Vietnam.', 'data/images/viD_img/Bo Bia (Vietnamese Spring Rolls with Jicama n Egg).jpg'),
('VN-0004','Bun Bo Hue (Spicy Vietnamese Beef Noodle Soup)', 'Bun Bo Hue is a popular Vietnamese noodle soup originating from the city of Hue in central Vietnam. It is known for its spicy and robust broth made with beef bones, lemongrass, and shrimp paste, along with tender slices of beef, pork knuckle, and pig''s blood. Bun Bo Hue is typically served with round rice noodles and garnished with fresh herbs, lime wedges, and shredded banana blossom.', 'data/images/viD_img/Bun Bo Hue (Spicy Vietnamese Beef Noodle Soup) 1.jpg'),
('VN-0005','Bun Moc (Pork and Mushroom Noodle Soup)', 'Bun Moc is a Vietnamese noodle soup made with ground pork and mushrooms. The broth is flavored with aromatics like ginger and fish sauce, and the soup is typically served with rice vermicelli noodles, fresh herbs, and a side of chili sauce. Bun Moc is a comforting and flavorful dish enjoyed throughout Vietnam.', 'data/images/viD_img/Bun Moc (Pork n Mushroom Noodle Soup).jpg'),
('VN-0006','Bun Rieu (Vietnamese Crab Noodle Soup)', 'Bun Rieu is a Vietnamese noodle soup known for its flavorful broth made with crab paste or crab meat, tomatoes, and fermented shrimp paste. The soup is typically served with rice vermicelli noodles, tofu, pork, and fresh herbs. Bun Rieu is a popular street food dish enjoyed throughout Vietnam.', 'data/images/viD_img/Bun Rieu ((Vietnamese Crab Noodle Soup).jpg'),
('VN-0007','Bun Thit Nuong_Ha Noi Version (Vietnamese Grilled Pork Noodle)', 'Bun Thit Nuong is a Vietnamese dish featuring grilled pork served over vermicelli noodles, topped with fresh herbs, pickled vegetables, and a savory sauce. This version is inspired by the cuisine of Hanoi, known for its subtle flavors and emphasis on freshness. It''s a light and refreshing meal commonly enjoyed throughout Vietnam.', 'data/images/viD_img/Bun Thit Nuong_Ha Noi Version (Vietnamese Grilled Pork Noodle) 1.jpg'),
('VN-0008','Bun Thit Nuong_Hoi An Version (Vietnamese Grilled Pork Noodle)', 'Bun Thit Nuong is a Vietnamese dish featuring grilled pork served over vermicelli noodles, topped with fresh herbs, pickled vegetables, and a savory sauce. This version is inspired by the cuisine of Hoi An, known for its vibrant flavors and mix of influences from Chinese, Japanese, and indigenous Vietnamese cuisines. It''s a delightful and satisfying dish commonly enjoyed throughout Vietnam.', 'data/images/viD_img/Bun Thit Nuong_Hoi An Version (Vietnamese Grilled Pork Noodle).jpg'),
('VN-0009','Ca Kho To (Vietnamese Braised Fish)', 'Ca Kho To is a traditional Vietnamese dish featuring catfish braised in a caramelized sauce made from fish sauce, sugar, and aromatics. The fish is cooked until tender and flavorful, with a slightly sweet and savory taste. Ca Kho To is often served with steamed rice and garnished with fresh herbs and sliced chili peppers.', 'data/images/viD_img/Ca Kho To (Vietnamese Braised Fish).jpg'),
('VN-0010','Canh Chua (Vietnamese Sour Soup)', 'Canh Chua is a traditional Vietnamese soup known for its sweet, sour, and savory flavors. It features a clear broth made from tamarind, pineapple, tomatoes, and aromatic herbs, along with shrimp, fish, or other proteins. Canh Chua is typically served with steamed rice and garnished with fresh herbs and chili peppers.', 'data/images/viD_img/Canh Chua (Vietnamese Sour Soup) 1.jpg'),
('VN-0011','Cao Lau Hoi An (Vietnamese Noodle Bowl)', 'Cao Lau is a specialty noodle dish from Hoi An, a historic town in central Vietnam. It features thick rice noodles, slices of pork, crispy pork rinds, fresh herbs, and a flavorful broth made with secret ingredients like ash water. Cao Lau is topped with bean sprouts, lettuce, and thinly sliced green onions, and it''s typically served with a side of chili sauce.', 'data/images/viD_img/Cao Lau Hoi An (Vietnamese Noodle Bowl) .jpg'),
('VN-0012','Goi Cuon Tom Thit (Vietnamese Spring Rolls)', 'Goi Cuon, also known as Vietnamese spring rolls or fresh summer rolls, are a popular Vietnamese appetizer made with shrimp, pork, vermicelli noodles, and fresh herbs wrapped in rice paper. They are light, refreshing, and often served with a peanut dipping sauce. Goi Cuon is a healthy and delicious snack enjoyed throughout Vietnam.', 'data/images/viD_img/Goi Cuon Tom Thit (Vietnamese Spring Rolls) 1.jpg'),
('VN-0013','Goi Xoai (Vietnamese Mango Salad)', 'Goi Xoai is a refreshing Vietnamese salad made with green mangoes, shrimp, herbs, and a tangy dressing. It''s a perfect balance of sweet, sour, salty, and spicy flavors, and it''s often served as a side dish or appetizer. Goi Xoai is a popular dish during the hot summer months in Vietnam.', 'data/images/viD_img/Goi Xoai (Vietnanese Mango Salad).jpg'),
('VN-0014','Mi Quang (Vietnamese Noodle with Pork n Shrimps)', 'Mi Quang is a Vietnamese noodle dish originating from the central region of Vietnam. It features wide rice noodles, pork, shrimp, and a flavorful broth made with turmeric and aromatics. Mi Quang is often garnished with peanuts, fresh herbs, and crispy rice crackers, and it''s typically served as a light meal or snack.', 'data/images/viD_img/Mi Quang (Vietnames Noodle with Pork n Shrimps) 1.jpg'),
('VN-0015','Nem Nuong (Vietnamese Grilled Pork Skewers)', 'Nem Nuong is a Vietnamese dish consisting of seasoned ground pork grilled on skewers. The pork is flavored with garlic, shallots, fish sauce, and sugar, giving it a savory and slightly sweet taste. Nem Nuong is often served as an appetizer or as part of a larger meal, and it''s typically accompanied by lettuce leaves, fresh herbs, and rice paper for wrapping.', 'data/images/viD_img/Nem Nuong (Vietnamese Grilled Pork Skewers) 1.jpg'),
('VN-0016','Pho Bo (Beef Pho)', 'Pho Bo is a traditional Vietnamese soup consisting of beef broth, rice noodles, and thinly sliced beef. It''s flavored with aromatic spices like star anise, cinnamon, and cloves, and it''s typically served with fresh herbs, bean sprouts, lime wedges, and chili peppers on the side. Pho Bo is a popular street food dish enjoyed throughout Vietnam.', 'data/images/viD_img/Pho Bo (Beef Pho) 1.jpg');

-- Insert data for Chinese recipes
INSERT INTO chinese_recipes (recipe_id, recipe_name, description, image_file) VALUES
('CN-0001','Beijing Kaoya', 'Beijing Kaoya, also known as Peking Duck, is a famous Chinese dish that features crispy duck skin and tender meat wrapped in thin pancakes with hoisin sauce, cucumber, and green onions. The duck is traditionally roasted until the skin is golden and crispy, resulting in a delightful combination of flavors and textures.', 'data/images/chiD_img/beijing_kaoya.jpg'),
('CN-0002','Crystal Dumplings', 'Crystal Dumplings, also called Har Gow, are translucent dumplings filled with shrimp and sometimes bamboo shoots. The dumpling wrapper is made from a combination of wheat starch and tapioca flour, giving it a chewy yet delicate texture. These dumplings are typically steamed and served as a delicious appetizer or snack.', 'data/images/chiD_img/crystal_dumplings.jpg'),
('CN-0003','Dapanji', 'Dapanji, or Big Plate Chicken, is a hearty Xinjiang dish consisting of tender chicken pieces, potatoes, bell peppers, and onions cooked in a rich and spicy tomato-based sauce. This dish is known for its bold flavors and generous portions, making it a favorite among those who enjoy spicy and comforting meals.', 'data/images/chiD_img/dapanji.jpg'),
('CN-0004','Dao xiao mian', 'Dao xiao mian, or Big Wok Noodles, is a popular street food dish originating from Lanzhou, China. It features hand-pulled noodles served in a flavorful beef broth topped with sliced beef, green onions, and sometimes cilantro. This dish is beloved for its simplicity and satisfying taste.', 'data/images/chiD_img/dao_xiao_mian.jpg'),
('CN-0005','Fried Rice', 'Fried Rice is a versatile Chinese dish made by stir-frying cooked rice with various ingredients such as eggs, vegetables, and meat or seafood. It is seasoned with soy sauce, oyster sauce, and other flavorings, giving it a savory and satisfying taste. Fried rice is a popular choice for using up leftover ingredients and is enjoyed as a quick and delicious meal.', 'data/images/chiD_img/fried_rice.jpg'),
('CN-0006','Mapo Tofu', 'Mapo Tofu is a classic Sichuan dish featuring soft tofu cubes and minced meat cooked in a spicy and flavorful sauce made from doubanjiang (broad bean paste), fermented black beans, garlic, ginger, and Sichuan peppercorns. It is typically garnished with chopped green onions and served with steamed rice, providing a satisfyingly spicy and numbing sensation.', 'data/images/chiD_img/mapo_tofu.jpg'),
('CN-0007','Spicy Kung Pao Chicken', 'Spicy Kung Pao Chicken is a popular Chinese stir-fry dish that features tender chicken pieces, peanuts, and dried chili peppers cooked in a spicy and tangy sauce made from soy sauce, vinegar, sugar, and Sichuan peppercorns. It is often garnished with green onions and served with steamed rice, offering a delightful balance of heat and flavor.', 'data/images/chiD_img/spicy_kung_pao_chicken.jpg'),
('CN-0008','Stir-fried Beef with Rice Noodles', 'Stir-fried Beef with Rice Noodles is a popular Cantonese dish consisting of tender beef slices, flat rice noodles, and crisp vegetables stir-fried together in a savory sauce made from oyster sauce, soy sauce, and other seasonings. This dish is quick and easy to prepare, making it a perfect choice for a delicious weeknight meal.', 'data/images/chiD_img/stir_fried_beef_with_rice_noodles.jpg'),
('CN-0009','Sweet and Sour Pork Tenderloin', 'Sweet and Sour Pork Tenderloin is a classic Chinese dish featuring crispy pork tenderloin pieces coated in a tangy sweet and sour sauce made from vinegar, sugar, ketchup, and soy sauce. It is typically served with bell peppers, onions, and pineapple chunks, creating a colorful and flavorful dish that is sure to satisfy your cravings.', 'data/images/chiD_img/sweet_and_sour_pork_tenderloin.jpg');
